[package]
name = "filter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prusti-contracts = { git  = "https://github.com/viperproject/prusti-dev.git"}

[lib]
crate-type = ["cdylib"]
